FROM rust:1.80 AS builder
WORKDIR /usr/src/eprofiler
COPY . .
RUN cargo install --path .

FROM debian

RUN apt-get update && apt-get install -y openssl && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/eprofiler /usr/local/bin/eprofiler
COPY config.json /
COPY ./www /www

# Copy SSL certificates to the container
#COPY certificate.crt /usr/local/share/ca-certificates/certificate.crt
# Update SSL certificates in the container
#RUN update-ca-certificates

CMD ["eprofiler"]
