"""
Django settings for consumer project.
Generated by 'django-admin startproject' using Django 5.1.
For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import logging
import os
from pathlib import Path

import environ

logger = logging.getLogger(__name__)

# Initialize environment
env = environ.Env(
    DEBUG=(bool, True)
)

# Define BASE_DIR as the project root.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from BASE_DIR
environ.Env.read_env(os.path.join(BASE_DIR, '.env.example'))

# Use environment variables for settings
DEBUG = env.bool("DEBUG", default=True)
SECRET_KEY = env("SECRET_KEY")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web_app.apps.entsoe',
    'web_app.apps.demonstrator',
    'web_app.apps.awattar.apps.AwattarConfig',
    'web_app.apps.predictions',
    'common_models.common_models_app.apps.CommonModelsConfig',
    'consumer.kafka_consumer.apps.KafkaConsumerConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'consumer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'consumer.wsgi.application'

# Database configuration using django-environ
DATABASES = {   
        'default': {  
           'ENGINE': 'django.db.backends.postgresql',
           'NAME': os.getenv('TIMESCALEDB_NAME', 'timescale'),
           'USER': os.getenv('TIMESCALEDB_USERNAME', 'postgres'),
           'PASSWORD': os.getenv('TIMESCALEDB_PASSWORD', 'eddie'),
           'HOST': os.getenv('TIMESCALEDB_HOST', 'timescale'),
           'PORT': os.getenv('TIMESCALEDB_PORT', '5432'),
        },
}

logger.debug("Using database: " + str(DATABASES['default']))

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'
STATIC_ROOT = '/app/staticfiles'


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
