# Generated by Django 5.1 on 2025-02-25 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteringPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metering_point', models.CharField(max_length=255)),
                ('connection_id', models.CharField(max_length=255)),
                ('data_need_id', models.CharField(max_length=255)),
                ('permission_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='marketprice_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['start_timestamp'], name='common_mode_start_t_4397ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('metering_interval', models.DurationField()),
                ('unit', models.CharField(max_length=50)),
                ('metering_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_metas', to='common_models_app.meteringpoint')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('unit', models.CharField(max_length=20)),
                ('prediction_value', models.FloatField()),
                ('total_next_day', models.FloatField()),
                ('time_series_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='common_models_app.timeseriesmeta')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('emission_value', models.FloatField()),
                ('unit', models.CharField(default='kgCO2eq', max_length=20)),
                ('time_series_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='common_models_app.timeseriesmeta')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('consumption_value', models.FloatField()),
                ('time_series_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='common_models_app.timeseriesmeta')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('street', models.CharField(max_length=250, null=True)),
                ('number', models.IntegerField(null=True)),
                ('postal_code', models.IntegerField(null=True)),
                ('city', models.IntegerField(null=True)),
                ('country', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meteringpoint',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models_app.userprofile'),
        ),
        migrations.AddIndex(
            model_name='timeseriesmeta',
            index=models.Index(fields=['start_datetime'], name='common_mode_start_d_5cbc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='predictiondata',
            index=models.Index(fields=['timestamp'], name='common_mode_timesta_e7397d_idx'),
        ),
        migrations.AddIndex(
            model_name='emissiondata',
            index=models.Index(fields=['timestamp'], name='common_mode_timesta_ba03c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emissiondata',
            unique_together={('time_series_meta', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='consumption',
            index=models.Index(fields=['timestamp'], name='common_mode_timesta_ff4b5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consumption',
            unique_together={('time_series_meta', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='meteringpoint',
            unique_together={('user_profile', 'metering_point')},
        ),
    ]
